import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { useTranslation } from "react-i18next";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Calculator, CheckCircle, XCircle, AlertCircle, Crown, Clock } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { supabase } from "@/integrations/supabase/client";
import { QuestionStep, TypeformInput, TypeformRadioGroup, TypeformCheckbox } from "./simulator/QuestionStep";
import { PhoneInput } from "./simulator/PhoneInput";

interface FormData {
  propertyValue: string;
  isMortgaged: string;
  amountPaid: string;
  hasNOC: boolean;
  propertyInName: string;
  presentInUAE: string;
  hasValidPassport: boolean;
  hasHealthInsurance: boolean;
  sponsorFamily: boolean;
  clientName: string;
  clientEmail: string;
  clientPhone: string;
  clientPhoneCountry: string;
  whatsappNumber: string;
  whatsappCountry: string;
}

interface SimulationResult {
  eligible: boolean;
  visaType: '2-year' | '10-year' | null;
  reasons: string[];
  requirements: string[];
  totalCost: number;
}

const TypeformStyleSimulator = () => {
  const { toast } = useToast();
  const navigate = useNavigate();
  const { t } = useTranslation();
  
  const [currentStep, setCurrentStep] = useState(1);
  const [isLoading, setIsLoading] = useState(false);
  const [formData, setFormData] = useState<FormData>({
    propertyValue: '',
    isMortgaged: '',
    amountPaid: '',
    hasNOC: false,
    propertyInName: '',
    presentInUAE: '',
    hasValidPassport: false,
    hasHealthInsurance: false,
    sponsorFamily: false,
    clientName: '',
    clientEmail: '',
    clientPhone: '',
    clientPhoneCountry: '+971',
    whatsappNumber: '',
    whatsappCountry: '+971',
  });

  const [result, setResult] = useState<SimulationResult | null>(null);
  const [showResults, setShowResults] = useState(false);

  const totalSteps = 7; // Étapes totales du formulaire

  // Fonction pour déterminer le type de visa selon le montant
  const getVisaType = (propertyValue: string) => {
    const value = parseInt(propertyValue.replace(/[^\d]/g, ''));
    if (value >= 2000000) return 'Golden Visa (10 ans)';
    if (value >= 750000) return 'Visa résidence (2 ans)';
    return null;
  };

  const saveFormDataToDatabase = async (simulationResult: SimulationResult) => {
    try {
      const propertyValue = parseInt(formData.propertyValue.replace(/[^\d]/g, ''));
      const amountPaid = formData.isMortgaged === 'yes' ? parseInt(formData.amountPaid.replace(/[^\d]/g, '')) : null;

      const { data, error } = await supabase
        .from('visa_cases')
        .insert({
          client_name: formData.clientName,
          client_email: formData.clientEmail,
          client_phone: formData.clientPhone,
          whatsapp_number: formData.whatsappNumber || null,
          visa_type: simulationResult.visaType || 'not-eligible',
          property_value: propertyValue,
          is_mortgaged: formData.isMortgaged === 'yes',
          amount_paid: amountPaid,
          has_noc: formData.hasNOC,
          property_in_name: formData.propertyInName,
          present_in_uae: formData.presentInUAE === 'yes',
          has_valid_passport: formData.hasValidPassport,
          has_health_insurance: formData.hasHealthInsurance,
          sponsor_family: formData.sponsorFamily,
          status: simulationResult.eligible ? 'nouveau' : 'non-eligible',
          estimated_cost: simulationResult.totalCost,
          notes: simulationResult.eligible ? 'Éligible via simulateur' : 'Non éligible: ' + simulationResult.reasons.join('; '),
          case_number: '' // Will be auto-generated by trigger
        });

      if (error) {
        console.error('Error saving form data:', error);
        toast({
          title: "Erreur",
          description: "Impossible de sauvegarder vos données. Veuillez réessayer.",
          variant: "destructive",
        });
      }
    } catch (error) {
      console.error('Error saving form data:', error);
    }
  };

  const calculateEligibility = (): SimulationResult => {
    const propertyValue = parseInt(formData.propertyValue.replace(/[^\d]/g, ''));
    const amountPaid = formData.isMortgaged === 'yes' ? parseInt(formData.amountPaid.replace(/[^\d]/g, '')) : propertyValue;
    
    const reasons: string[] = [];
    const requirements: string[] = [];
    let eligible = true;
    let visaType: '2-year' | '10-year' | null = null;

    // Check property value thresholds
    if (propertyValue >= 2000000) {
      visaType = '10-year';
      requirements.push(t('simulator.result.requirements.goldenVisa'));
    } else if (propertyValue >= 750000) {
      visaType = '2-year';
      requirements.push(t('simulator.result.requirements.residence'));
    } else {
      eligible = false;
      reasons.push(`Valeur propriété insuffisante (${propertyValue.toLocaleString()} AED). Minimum 750,000 AED requis.`);
    }

    // Check mortgage conditions
    if (formData.isMortgaged === 'yes') {
      const paidPercentage = (amountPaid / propertyValue) * 100;
      if (paidPercentage < 50) {
        eligible = false;
        reasons.push(`Seulement ${paidPercentage.toFixed(1)}% payé. Minimum 50% requis pour propriété hypothéquée.`);
      }
      if (!formData.hasNOC) {
        eligible = false;
        reasons.push('Lettre de non-objection (NOC) de la banque requise.');
      }
    }

    // Check other requirements
    if (formData.propertyInName === 'no') {
      eligible = false;
      reasons.push('La propriété doit être au nom du demandeur ou partagée (époux/épouse).');
    }

    if (formData.presentInUAE === 'no') {
      eligible = false;
      reasons.push('Présence physique aux EAU requise lors de la demande.');
    }

    if (!formData.hasValidPassport) {
      eligible = false;
      reasons.push('Passeport valide requis.');
    }

    if (!formData.hasHealthInsurance) {
      eligible = false;
      reasons.push('Assurance santé valide requise.');
    }

    // Additional requirements for eligible cases
    if (eligible) {
      requirements.push(t('simulator.result.requirements.goodConduct'));
      requirements.push(t('simulator.result.requirements.photos'));
      requirements.push(t('simulator.result.requirements.application'));
      if (formData.sponsorFamily) {
        requirements.push(t('simulator.result.requirements.familyDocs'));
      }
    }

    return {
      eligible,
      visaType,
      reasons,
      requirements,
      totalCost: 3500 + (eligible && visaType === '10-year' ? 2000 : 1000)
    };
  };

  const handleNext = async () => {
    // Check if we're on the last step
    const isLastStep = (formData.isMortgaged === 'no' && currentStep === 7) || 
                       (formData.isMortgaged === 'yes' && currentStep === 8);
    
    if (isLastStep) {
      setIsLoading(true);
      
      // Simulate API call
      await new Promise(resolve => setTimeout(resolve, 1500));
      
      const simulationResult = calculateEligibility();
      
      // Save data to database
      await saveFormDataToDatabase(simulationResult);
      
      setResult(simulationResult);
      setIsLoading(false);
      setShowResults(true);

      if (simulationResult.eligible) {
        toast({
          title: t('simulator.result.congratulations'),
          description: t('simulator.result.eligibleFor', { 
            visaType: simulationResult.visaType === '10-year' ? t('simulator.result.goldenVisa10') : t('simulator.result.residence2')
          }),
        });
      } else {
        toast({
          title: t('simulator.result.notEligibleMsg'),
          description: t('simulator.result.seeConditions'),
          variant: "destructive",
        });
      }
    } else {
      setCurrentStep(prev => prev + 1);
    }
  };

  const handlePrevious = () => {
    if (currentStep > 1) {
      setCurrentStep(prev => prev - 1);
    }
  };

  const canGoNext = () => {
    switch (currentStep) {
      case 1:
        return formData.propertyValue.length > 0;
      case 2:
        return formData.isMortgaged.length > 0;
      case 3:
        return formData.isMortgaged === 'no' || (formData.amountPaid.length > 0 && formData.hasNOC);
      case 4:
        return formData.propertyInName.length > 0;
      case 5:
        return formData.presentInUAE.length > 0;
      case 6:
        return formData.hasValidPassport && formData.hasHealthInsurance;
      case 7:
        return formData.clientName.length > 0 && formData.clientEmail.length > 0;
      case 8:
        return formData.clientPhone.length > 0;
      default:
        return false;
    }
  };

  const getDisplayStep = () => {
    if (formData.isMortgaged === 'no' && currentStep > 2) {
      return currentStep - 1;
    }
    return currentStep;
  };

  const getTotalDisplaySteps = () => {
    return formData.isMortgaged === 'no' ? 7 : 8;
  };

  if (showResults && result) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center p-4">
        <div className="w-full max-w-4xl">
          <Card className={`${result.eligible ? 'border-success' : 'border-destructive'} shadow-luxury animate-fade-in`}>
            <CardHeader>
              <CardTitle className="flex items-center space-x-2 justify-center">
                {result.eligible ? (
                  <>
                    <CheckCircle className="w-6 h-6 text-success" />
                    <span className="text-success text-2xl">{t('simulator.result.eligible')}</span>
                  </>
                ) : (
                  <>
                    <XCircle className="w-6 h-6 text-destructive" />
                    <span className="text-destructive text-2xl">{t('simulator.result.notEligible')}</span>
                  </>
                )}
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-6">
              {result.eligible ? (
                <div className="space-y-6">
                  <div className="flex items-center space-x-3 p-4 bg-success/10 rounded-lg">
                    {result.visaType === '10-year' ? (
                      <Crown className="w-8 h-8 text-success" />
                    ) : (
                      <Clock className="w-8 h-8 text-success" />
                    )}
                    <div>
                      <h3 className="font-semibold text-lg">
                        {result.visaType === '10-year' ? t('simulator.result.goldenVisa10') : t('simulator.result.residence2')}
                      </h3>
                      <p className="text-muted-foreground">
                        {result.visaType === '10-year' 
                          ? t('simulator.result.goldenVisaDesc')
                          : t('simulator.result.residenceDesc')
                        }
                      </p>
                    </div>
                  </div>

                  <div>
                    <h4 className="font-medium mb-3">{t('simulator.result.documentsRequired')}</h4>
                    <ul className="space-y-2">
                      {result.requirements.map((req, idx) => (
                        <li key={idx} className="flex items-center space-x-2">
                          <CheckCircle className="w-4 h-4 text-success" />
                          <span className="text-sm">{req}</span>
                        </li>
                      ))}
                    </ul>
                  </div>

                  <div className="p-4 bg-card rounded-lg border">
                    <h4 className="font-medium mb-2">{t('simulator.result.totalCost')}</h4>
                    <div className="text-2xl font-bold text-primary">
                      AED {result.totalCost.toLocaleString()}
                    </div>
                    <p className="text-sm text-muted-foreground mt-1">
                      {t('simulator.result.totalCostDesc')}
                    </p>
                  </div>

                  <div className="flex flex-col sm:flex-row gap-3">
                    <Button 
                      variant="premium" 
                      size="lg" 
                      className="flex-1"
                      onClick={() => navigate('/application')}
                    >
                      {t('simulator.result.startApplication')}
                    </Button>
                    <Button variant="outline" size="lg" className="flex-1">
                      {t('simulator.result.downloadReport')}
                    </Button>
                  </div>
                </div>
              ) : (
                <div className="space-y-4">
                  <div>
                    <h4 className="font-medium mb-3 flex items-center space-x-2">
                      <AlertCircle className="w-5 h-5 text-destructive" />
                      <span>{t('simulator.result.conditionsNotMet')}</span>
                    </h4>
                    <ul className="space-y-2">
                      {result.reasons.map((reason, idx) => (
                        <li key={idx} className="flex items-start space-x-2">
                          <XCircle className="w-4 h-4 text-destructive mt-0.5" />
                          <span className="text-sm">{reason}</span>
                        </li>
                      ))}
                    </ul>
                  </div>

                  <div className="p-4 bg-muted rounded-lg">
                    <h4 className="font-medium mb-2">{t('simulator.result.whatToDo')}</h4>
                    <p className="text-sm text-muted-foreground">
                      {t('simulator.result.contactAdvice')}
                    </p>
                  </div>

                  <Button variant="outline" size="lg" className="w-full">
                    {t('simulator.result.consultAdvisor')}
                  </Button>
                </div>
              )}
            </CardContent>
          </Card>
        </div>
      </div>
    );
  }

  return (
    <div>
      {/* Header section - More compact */}
      <section className="py-4 bg-background">
        <div className="container mx-auto px-4 text-center">
          <Badge variant="outline" className="mb-4">
            <Calculator className="w-4 h-4 mr-2" />
            {t('simulator.badge')}
          </Badge>
          <h2 className="text-2xl md:text-3xl font-bold mb-3">
            {t('simulator.title')}
          </h2>
          <p className="text-base text-muted-foreground max-w-2xl mx-auto">
            {t('simulator.description')}
          </p>
        </div>
      </section>

      {/* Questions */}
      {currentStep === 1 && (
        <QuestionStep
          step={getDisplayStep()}
          totalSteps={getTotalDisplaySteps()}
          title={t('simulator.form.step1.propertyValue.label')}
          subtitle={t('simulator.form.step1.propertyValue.hint')}
          onNext={handleNext}
          onPrevious={handlePrevious}
          canGoNext={canGoNext()}
          canGoPrevious={false}
        >
          <div className="space-y-4">
            <TypeformInput
              placeholder={t('simulator.form.step1.propertyValue.placeholder')}
              value={formData.propertyValue}
              onChange={(value) => setFormData(prev => ({ ...prev, propertyValue: value }))}
            />
            
            {/* Affichage du type de visa éligible */}
            {formData.propertyValue && getVisaType(formData.propertyValue) && (
              <div className="mt-4 p-4 bg-green-50 border border-green-200 rounded-lg">
                <div className="flex items-center space-x-2">
                  <div className="w-2 h-2 bg-green-500 rounded-full"></div>
                  <span className="text-green-700 font-medium">
                    Éligible pour : {getVisaType(formData.propertyValue)}
                  </span>
                </div>
                <p className="text-sm text-green-600 mt-1">
                  {parseInt(formData.propertyValue.replace(/[^\d]/g, '')) >= 2000000 
                    ? "Propriété de 2M AED+ = Golden Visa de 10 ans"
                    : "Propriété de 750K-2M AED = Visa de résidence de 2 ans"
                  }
                </p>
              </div>
            )}

            {/* Message si montant insuffisant */}
            {formData.propertyValue && !getVisaType(formData.propertyValue) && parseInt(formData.propertyValue.replace(/[^\d]/g, '')) > 0 && (
              <div className="mt-4 p-4 bg-red-50 border border-red-200 rounded-lg">
                <div className="flex items-center space-x-2">
                  <div className="w-2 h-2 bg-red-500 rounded-full"></div>
                  <span className="text-red-700 font-medium">
                    Montant insuffisant
                  </span>
                </div>
                <p className="text-sm text-red-600 mt-1">
                  Minimum 750,000 AED requis pour obtenir un visa de résidence
                </p>
              </div>
            )}
          </div>
        </QuestionStep>
      )}

      {currentStep === 2 && (
        <QuestionStep
          step={getDisplayStep()}
          totalSteps={getTotalDisplaySteps()}
          title={t('simulator.form.step1.isMortgaged.label')}
          onNext={handleNext}
          onPrevious={handlePrevious}
          canGoNext={canGoNext()}
          canGoPrevious={true}
        >
          <TypeformRadioGroup
            value={formData.isMortgaged}
            onValueChange={(value) => setFormData(prev => ({ ...prev, isMortgaged: value }))}
            onNext={handleNext} // Ajout de la navigation automatique
            options={[
              {
                value: 'no',
                label: t('simulator.form.step1.isMortgaged.no.title'),
                description: t('simulator.form.step1.isMortgaged.no.description')
              },
              {
                value: 'yes',
                label: t('simulator.form.step1.isMortgaged.yes.title'),
                description: t('simulator.form.step1.isMortgaged.yes.description')
              }
            ]}
          />
        </QuestionStep>
      )}

      {currentStep === 3 && formData.isMortgaged === 'yes' && (
        <QuestionStep
          step={getDisplayStep()}
          totalSteps={getTotalDisplaySteps()}
          title={t('simulator.form.step1.amountPaid.label')}
          subtitle={formData.propertyValue && formData.amountPaid ? 
            t('simulator.form.step1.amountPaid.percentage', { 
              percent: ((parseInt(formData.amountPaid.replace(/[^\d]/g, '')) / parseInt(formData.propertyValue.replace(/[^\d]/g, ''))) * 100).toFixed(1) 
            }) : ''
          }
          onNext={handleNext}
          onPrevious={handlePrevious}
          canGoNext={canGoNext()}
          canGoPrevious={true}
        >
          <div className="space-y-4">
            <TypeformInput
              placeholder={t('simulator.form.step1.amountPaid.placeholder')}
              value={formData.amountPaid}
              onChange={(value) => setFormData(prev => ({ ...prev, amountPaid: value }))}
            />
            
            <TypeformCheckbox
              checked={formData.hasNOC}
              onCheckedChange={(checked) => setFormData(prev => ({ ...prev, hasNOC: checked }))}
              label={t('simulator.form.step1.hasNOC.title')}
              description={t('simulator.form.step1.hasNOC.description')}
            />
          </div>
        </QuestionStep>
      )}

      {((currentStep === 3 && formData.isMortgaged === 'no') || (currentStep === 4 && formData.isMortgaged === 'yes')) && (
        <QuestionStep
          step={getDisplayStep()}
          totalSteps={getTotalDisplaySteps()}
          title={t('simulator.form.step2.propertyInName.label')}
          onNext={handleNext}
          onPrevious={handlePrevious}
          canGoNext={canGoNext()}
          canGoPrevious={true}
        >
           <TypeformRadioGroup
            value={formData.propertyInName}
            onValueChange={(value) => setFormData(prev => ({ ...prev, propertyInName: value }))}
            onNext={handleNext} // Ajout de la navigation automatique
            options={[
              {
                value: 'yes',
                label: t('simulator.form.step2.propertyInName.yes.title'),
                description: t('simulator.form.step2.propertyInName.yes.description')
              },
              {
                value: 'shared',
                label: t('simulator.form.step2.propertyInName.shared.title'),
                description: t('simulator.form.step2.propertyInName.shared.description')
              },
              {
                value: 'no',
                label: t('simulator.form.step2.propertyInName.no.title'),
                warning: 'Non éligible'
              }
            ]}
          />
        </QuestionStep>
      )}

      {((currentStep === 4 && formData.isMortgaged === 'no') || (currentStep === 5 && formData.isMortgaged === 'yes')) && (
        <QuestionStep
          step={getDisplayStep()}
          totalSteps={getTotalDisplaySteps()}
          title={t('simulator.form.step2.presentInUAE.label')}
          onNext={handleNext}
          onPrevious={handlePrevious}
          canGoNext={canGoNext()}
          canGoPrevious={true}
        >
           <TypeformRadioGroup
            value={formData.presentInUAE}
            onValueChange={(value) => setFormData(prev => ({ ...prev, presentInUAE: value }))}
            onNext={handleNext} // Ajout de la navigation automatique
            options={[
              {
                value: 'yes',
                label: t('simulator.form.step2.presentInUAE.yes.title'),
                description: t('simulator.form.step2.presentInUAE.yes.description')
              },
              {
                value: 'no',
                label: t('simulator.form.step2.presentInUAE.no.title'),
                warning: 'Présence obligatoire aux EAU'
              }
            ]}
          />
        </QuestionStep>
      )}

      {((currentStep === 5 && formData.isMortgaged === 'no') || (currentStep === 6 && formData.isMortgaged === 'yes')) && (
        <QuestionStep
          step={getDisplayStep()}
          totalSteps={getTotalDisplaySteps()}
          title={t('simulator.form.step3.documentsLabel')}
          onNext={handleNext}
          onPrevious={handlePrevious}
          canGoNext={canGoNext()}
          canGoPrevious={true}
        >
          <div className="space-y-4">
            <TypeformCheckbox
              checked={formData.hasValidPassport}
              onCheckedChange={(checked) => setFormData(prev => ({ ...prev, hasValidPassport: checked }))}
              label={t('simulator.form.step3.hasValidPassport.title')}
              description={t('simulator.form.step3.hasValidPassport.description')}
            />
            
            <TypeformCheckbox
              checked={formData.hasHealthInsurance}
              onCheckedChange={(checked) => setFormData(prev => ({ ...prev, hasHealthInsurance: checked }))}
              label={t('simulator.form.step3.hasHealthInsurance.title')}
              description={t('simulator.form.step3.hasHealthInsurance.description')}
            />
          </div>
        </QuestionStep>
      )}

      {/* Step - Family sponsoring (optional) */}
      {((currentStep === 5 && formData.isMortgaged === 'no') || (currentStep === 6 && formData.isMortgaged === 'yes')) && (
        <QuestionStep
          step={getDisplayStep()}
          totalSteps={getTotalDisplaySteps()}
          title="Family Sponsoring"
          subtitle="Do you want to sponsor family members? (Optional)"
          onNext={handleNext}
          onPrevious={handlePrevious}
          canGoNext={true}
          canGoPrevious={true}
        >
          <TypeformCheckbox
            checked={formData.sponsorFamily}
            onCheckedChange={(checked) => setFormData(prev => ({ ...prev, sponsorFamily: checked }))}
            label={t('simulator.form.step3.sponsorFamily.title')}
            description={t('simulator.form.step3.sponsorFamily.description')}
          />
        </QuestionStep>
      )}

      {/* Step - Contact information */}
      {((currentStep === 6 && formData.isMortgaged === 'no') || (currentStep === 7 && formData.isMortgaged === 'yes')) && (
        <QuestionStep
          step={getDisplayStep()}
          totalSteps={getTotalDisplaySteps()}
          title="Informations de contact"
          subtitle="Veuillez renseigner vos informations de contact"
          onNext={handleNext}
          onPrevious={handlePrevious}
          canGoNext={canGoNext()}
          canGoPrevious={true}
          isLoading={isLoading}
        >
          <div className="space-y-6">
            <TypeformInput
              placeholder="Votre nom complet"
              value={formData.clientName}
              onChange={(value) => setFormData(prev => ({ ...prev, clientName: value }))}
            />
            
            <TypeformInput
              placeholder="Votre adresse email"
              value={formData.clientEmail}
              onChange={(value) => setFormData(prev => ({ ...prev, clientEmail: value }))}
            />

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Numéro de téléphone
              </label>
              <PhoneInput
                placeholder="Numéro de téléphone"
                value={formData.clientPhone}
                onChange={(value) => setFormData(prev => ({ ...prev, clientPhone: value }))}
                onCountryChange={(country) => setFormData(prev => ({ ...prev, clientPhoneCountry: country.dialCode }))}
              />
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Numéro WhatsApp (optionnel)
              </label>
              <PhoneInput
                placeholder="Numéro WhatsApp"
                value={formData.whatsappNumber}
                onChange={(value) => setFormData(prev => ({ ...prev, whatsappNumber: value }))}
                onCountryChange={(country) => setFormData(prev => ({ ...prev, whatsappCountry: country.dialCode }))}
              />
            </div>
          </div>
        </QuestionStep>
       )}
    </div>
  );
};

export default TypeformStyleSimulator;