// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yinpfuvkvyohghpbtljp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpbnBmdXZrdnlvaGdocGJ0bGpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxMzU4NDQsImV4cCI6MjA3NDcxMTg0NH0.X-QOEvTYLb5Rga6cmCpFRG79sPIY4_H1JgXuscDXJFk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});